### ISSUE TITLE
Update manual test cases in TestRail for DBR

### ISSUE THREAD

**Issue by LisaGrey** [patracorp/QA-DBR#1]
The goal is complete coverage of existing functionality.

**Comment by LakshmilavanyaD** [comment]
Update the existing manual test cases as per the review comments provided by Lisa

**Comment by LisaGrey** [comment]
@renukaGundu and @LakshmilavanyaD please update the priorities of the DBR test cases as part of this task. Recall the preferred distribution is:

•	Critical/BVT around 10-15%
•	High around 20-30%
•	Medium around 40-60%
•	Low around 10-15%

**Comment by LakshmilavanyaD** [comment]
Updated the priorities of the DBR test cases.

**Comment by LakshmilavanyaD** [comment]
@LisaGrey, @renukaGundu  - Please verify the same

**Comment by LisaGrey** [comment]
@LakshmilavanyaD priority distribution is good and specific priorities of test cases are also good. Keeping this as In Progress until the manual test case edits are completed.

**Comment by LisaGrey** [comment]
Confirmed manual test case edits are complete - Closing this task.

**Comment by LakshmilavanyaD** [comment]
@LisaGrey 

Added the test cases for KPIs and Folder Movements for DBR application.
https://patra.testrail.io/index.php?/suites/view/47&group_by=cases:section_id&group_order=asc 

and updated the priorities as well.
Requesting you to review and close the task. Please let me know if any.
ThankYou!

**Comment by LakshmilavanyaD** [comment]
Thanks Lisa !
